name: vizeyes
channels:
  - conda-forge
dependencies:
  - matplotlib=3.9.3
  - numpy=2.1.3
  - pandas=2.2.3
  - flake8
  - pytest
  - pip 
  - ipykernel
  - pip:
      - -e git+https://github.com/BrendaQiu/eyelinkio.git@trial_info#egg=eyelinkio
      - -e . 








