name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0} 
    steps:
    - uses: actions/checkout@v4
  
    - name: setup miniforge
      uses: conda-incubator/setup-miniconda@v3
      with: 
        python-version: "3.12" 
        environment-file: environment.yml
        activate-environment: vizeyes
    - name: Conda Info
      run: |
        conda init
        conda activate vizeyes
        conda env list
        conda info -a
        conda list

    - name: Install current project 
      run: |
        pip install -e . --no-deps

    - name: Lint with flake8
      run: |
        python -c "import flake8; print(flake8.__version__)"
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
